#!/bin/sh
# Created Wed Sep 15 14:45:06 AKDT 2010
# by Raymond E. Marcil <marcilr@gmail.com>
#
# This script sets the svn:externals property from repos listed
# in svn_ext_val.txt  Then checks them out.
#


#
# Text file with list of repos in svn directory to checkout/update.
# This can include repo directories with repos.
#
REPOS=./svn_ext_val.txt

#
# UAA ITS repo directory for \\Anc-srv01\CodeRepository\* checkouts.
#
ITS=00ITS

#
# Binaries
#
BASENAME=/usr/bin/basename
HOSTNAME=/bin/hostname
SVN=/usr/bin/svn
XARGS=/usr/bin/xargs

#
# Extract directory name from full present working directory
# path.  This always for abstract use in different home 
# directories or base paths.
#
PWD=`pwd | ${XARGS} ${BASENAME}`
echo "PWD: ${PWD}"

# Get hostname value.
HOSTNAMEVAL=`${HOSTNAME}`
echo "HOSTNAMEVAL: ${HOSTNAMEVAL}"


#
# For UAA ITS boothite workstation:
# o Set custom svn location.
# o Checkout 00ITS repo directory for UAA ITS work repos.
#
if [ "${HOSTNAMEVAL}" = "boothite" ]; then
  SVN=/usr/local/subversion/bin/svn

  #
  # If present working directory is "svn" checkout
  # UAA ITS CodePository work repos.
  #
  if [ ${PWD} = "svn" ]; then

    # Checkout work repos.
    if [ ! -d ${ITS} ]; then
      ${SVN} co svn+ssh://home/data/svnroot/${ITS}/${ITS}
    fi

    #
    # If present update svn_ext_val.txt file.
    #
    if [ -f ${ITS}/${REPOS} ]; then
      ${SVN} up ${ITS}/${REPOS}
      ${SVN} propset svn:externals . -F ${ITS}/${REPOS}
    fi

    #
    # Updated UAA ITS repos.
    #
    ${SVN} up ${ITS}

  fi

fi


#
# If present update svn_ext_val.txt file.  Set svn:externals
# property from svn_ext_val.txt file with list of repositories
# for svn/ directory.
# 
#
if [ -f ${REPOS} ]; then 
  ${SVN} up ${REPOS}
  ${SVN} propset svn:externals . -F ${REPOS}
fi

#
# Update svn directory.  i.e. Checkout repositories.
#
${SVN} up
